---
- hosts: all:!vyatta-*
  tasks:
  - apt: update_cache=yes cache_valid_time=3600
  - name: Patch CVE-2017-5335 CVE-2017-5336 CVE-2017-5337 CVE-2017-3735 CVE-2017-1000257
    apt: pkg={{ item }} state=latest
    with_items:
      - libgnutls26
      - openssl
      - curl
      - libcurl3
      - openssh-server
    notify: restart haproxy
    register: result
    until: result|succeeded
    retries: 5
  handlers:
  - name: restart haproxy
    shell: service haproxy status && service haproxy restart || true
